# Generated by Django 4.0 on 2022-07-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('connection_type', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=70)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.BigIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dongle_recharge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('benefits', models.CharField(max_length=150)),
                ('validity', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('card_num', models.BigIntegerField()),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='postpaid_recharge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('benefits', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prepaid_recharge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('benefits', models.CharField(max_length=150)),
                ('validity', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
